import type { Metadata } from 'next';
import { Lato } from 'next/font/google';

import localFont from 'next/font/local';
import './globals.css';
import ToastContainer from '@/components/Toast/ToastContainer';
import { Suspense } from 'react';
import ReactQueryProvider from '@/utils/api/ReactQueryProvider';
import NextTopLoader from 'nextjs-toploader';
const lato = Lato({
    display: 'swap',
    subsets: ['latin'],
    weight: ['300', '400', '700', '900'],
    variable: '--font-lato',
});

const estedad = localFont({
    src: [
        {
            path: '../../public/fonts/estedad/Estedad-Thin.ttf',
            weight: '100',
            style: 'normal',
        },
        {
            path: '../../public/fonts/estedad/Estedad-Light.ttf',
            weight: '300',
            style: 'normal',
        },
        {
            path: '../../public/fonts/estedad/Estedad-Regular.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../public/fonts/estedad/Estedad-SemiBold.ttf',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../../public/fonts/estedad/Estedad-Bold.ttf',
            weight: '700',
            style: 'normal',
        },
        {
            path: '../../public/fonts/estedad/Estedad-Black.ttf',
            weight: '900',
            style: 'normal',
        },
    ],
    variable: '--font-estedad',
});
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='fa'
            dir='rtl'
            className={`antialiased overflow-x-hidden ${estedad.variable} ${lato.variable}`}
        >
            <body>
                <ReactQueryProvider>
                    <NextTopLoader
                        color='#ce4648'
                        shadow='0 0 10px #ce4648,0 0 5px #ce4648'
                        showSpinner={false}
                    />

                    <Suspense>
                        <ToastContainer />
                    </Suspense>
                    {children}
                </ReactQueryProvider>
            </body>
        </html>
    );
}

